services:
  back:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - './:/app'
    ports:
      - '3000:3000'
    environment:
      - REDIS_URL=redis://redis:6379
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    restart: always
    image: mysql:8.1
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
